# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.13.0
      with:
        checkout-fetch-depth: 0
        java-version: 21
        java-distribution: temurin
        maven-version: 3.9.6

    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dmaven.test.skip

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -Dmaven.test.skip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
